package com.example.noteapp.appSteps_ForLearning

/**      steps
 *1 domain.model
 *2 data.data_source.NoteDao
 *3 data.data_source.NoteDatabase
 *4 domain.repository.NoteRepository
 *5 data.repository.NoteRepositoryImpl
 *6 domain.use_case.GetNote
 *7 domain.util.OrderType
 *8 domain.util.NoteOrder
 *9 domain.use_case.DeleteNote
 *10 domain.use_case.NotesUseCases
 *11 noteapp.NoteApp
 *12 presentation.notes.NoteState
 *13 presentation.notes.NotesEvent
 *14 presentation.notes.NotesViewModel
 *15 domain.use_case.AddNote
 *16 presentation.notes.components.DefaultRadioButton
 *17 presentation.notes.components.OrderSection
 *18 presentation.notes.NotesScreen
 *19 domain.use_case.GetNote
 *20 presentation.add_edit_note.NoteTextFieldState
 *21 presentation.add_edit_note.AddEditNoteViewModel
 *22 presentation.add_edit_note.AddEditNoteEvent
 *23 add_edit_note.components.TransparentHintTextField
 *24 presentation.add_edit_note.AddEditNoteScreen
 *25 presentation.util.Screen
 *26 MainActivity
 */